//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMART.WCS.Resource.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SMART.WCS.Resource.Language.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Analysis과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_ANL {
            get {
                return ResourceManager.GetString("(MENU)ANL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_ANL01 {
            get {
                return ResourceManager.GetString("(MENU)ANL01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_ANL0101 {
            get {
                return ResourceManager.GetString("(MENU)ANL0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_ANL0102 {
            get {
                return ResourceManager.GetString("(MENU)ANL0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM {
            get {
                return ResourceManager.GetString("(MENU)COM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM01 {
            get {
                return ResourceManager.GetString("(MENU)COM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0101 {
            get {
                return ResourceManager.GetString("(MENU)COM0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0102 {
            get {
                return ResourceManager.GetString("(MENU)COM0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu Management과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0103 {
            get {
                return ResourceManager.GetString("(MENU)COM0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0104 {
            get {
                return ResourceManager.GetString("(MENU)COM0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0105 {
            get {
                return ResourceManager.GetString("(MENU)COM0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0106 {
            get {
                return ResourceManager.GetString("(MENU)COM0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM02 {
            get {
                return ResourceManager.GetString("(MENU)COM02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0201 {
            get {
                return ResourceManager.GetString("(MENU)COM0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0202 {
            get {
                return ResourceManager.GetString("(MENU)COM0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0203 {
            get {
                return ResourceManager.GetString("(MENU)COM0203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0204 {
            get {
                return ResourceManager.GetString("(MENU)COM0204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0205 {
            get {
                return ResourceManager.GetString("(MENU)COM0205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0206 {
            get {
                return ResourceManager.GetString("(MENU)COM0206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0207 {
            get {
                return ResourceManager.GetString("(MENU)COM0207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0208 {
            get {
                return ResourceManager.GetString("(MENU)COM0208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM03 {
            get {
                return ResourceManager.GetString("(MENU)COM03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0301 {
            get {
                return ResourceManager.GetString("(MENU)COM0301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0302 {
            get {
                return ResourceManager.GetString("(MENU)COM0302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0303 {
            get {
                return ResourceManager.GetString("(MENU)COM0303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QPS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM04 {
            get {
                return ResourceManager.GetString("(MENU)COM04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_COM0401 {
            get {
                return ResourceManager.GetString("(MENU)COM0401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Favorite과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_FVRT {
            get {
                return ResourceManager.GetString("(MENU)FVRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Optimization과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT {
            get {
                return ResourceManager.GetString("(MENU)OPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   QPS과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT01 {
            get {
                return ResourceManager.GetString("(MENU)OPT01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0101 {
            get {
                return ResourceManager.GetString("(MENU)OPT0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0102 {
            get {
                return ResourceManager.GetString("(MENU)OPT0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0103 {
            get {
                return ResourceManager.GetString("(MENU)OPT0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0104 {
            get {
                return ResourceManager.GetString("(MENU)OPT0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0105 {
            get {
                return ResourceManager.GetString("(MENU)OPT0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_OPT0106 {
            get {
                return ResourceManager.GetString("(MENU)OPT0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Plan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN {
            get {
                return ResourceManager.GetString("(MENU)PLN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Order과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN01 {
            get {
                return ResourceManager.GetString("(MENU)PLN01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN0101 {
            get {
                return ResourceManager.GetString("(MENU)PLN0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN0102 {
            get {
                return ResourceManager.GetString("(MENU)PLN0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Job Plan과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN02 {
            get {
                return ResourceManager.GetString("(MENU)PLN02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN0201 {
            get {
                return ResourceManager.GetString("(MENU)PLN0201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PLN0202 {
            get {
                return ResourceManager.GetString("(MENU)PLN0202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS {
            get {
                return ResourceManager.GetString("(MENU)PRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sorter과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS01 {
            get {
                return ResourceManager.GetString("(MENU)PRS01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS0101 {
            get {
                return ResourceManager.GetString("(MENU)PRS0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS0102 {
            get {
                return ResourceManager.GetString("(MENU)PRS0102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS0103 {
            get {
                return ResourceManager.GetString("(MENU)PRS0103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_PRS0104 {
            get {
                return ResourceManager.GetString("(MENU)PRS0104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_SCA {
            get {
                return ResourceManager.GetString("(MENU)SCA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_SCA01 {
            get {
                return ResourceManager.GetString("(MENU)SCA01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Monitoring과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string _MENU_SCA0101 {
            get {
                return ResourceManager.GetString("(MENU)SCA0101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string CELL_TYPE_MGT {
            get {
                return ResourceManager.GetString("CELL_TYPE_MGT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EQP_ID_REQ {
            get {
                return ResourceManager.GetString("EQP_ID_REQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXCEL_DOWNLOAD {
            get {
                return ResourceManager.GetString("EXCEL_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Excel Upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string EXCEL_UPLOAD {
            get {
                return ResourceManager.GetString("EXCEL_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string LOC_BTCH_INFO {
            get {
                return ResourceManager.GetString("LOC_BTCH_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Add과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ROW_ADD {
            get {
                return ResourceManager.GetString("ROW_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row Delete과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string ROW_DEL {
            get {
                return ResourceManager.GetString("ROW_DEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Search과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SEARCH {
            get {
                return ResourceManager.GetString("SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string SKU_CELL_TYPE_MGT {
            get {
                return ResourceManager.GetString("SKU_CELL_TYPE_MGT", resourceCulture);
            }
        }
    }
}
